version: "3.8"
services:
  server:
    build: ./server
    container_name: server_c
    ports:
      - '4000:4000'
    volumes:
      - ./server:/app
      - /app/node_modules
  client:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true